### ISSUE TITLE
Make templates inherit css styles

### ISSUE THREAD

**Issue by gaoDean** [18alantom/strawberry#17]
I have seen that the templates use the shadow DOM. Is there a way to make the template inherit the css of the document?

**Comment by gaoDean** [comment]
(Other than copying in all the css files into the template)

**Comment by nateabele** [comment]
Yeah, I would be interested in this as well—the Shadow DOM is kind of a jerk. @18alantom thoughts on enabling pass-through elements here? Should be a matter of patching things [somewhere in this neighborhood](https://github.com/18alantom/strawberry/blob/main/index.ts#L1125), but obviously it's more of a design question.

**Comment by 18alantom** [comment]
Agreed, I did not want to use the shadow DOM, but the WebComponents API is a bit unfortunate, and I'm not sure how to go about this.

I'll state the problem here for future reference, if you or anyone else who sees this has ideas or an optimal compromise please let me know.

---

There are two ways of registering components:
1. [Autonomous custom elements](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements#autonomous_custom_elements)
2. [Customized built-in elements](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements#autonomous_custom_elements)


**Autonomous custom elements** is what Strawberry uses. This is because it allows mentioning elements using custom tag names. Its biggest caveat is it doesn't allow extending pre-existing elements (eg, `<div>`).

On doing so one receives the following error:

```
Uncaught TypeError: Illegal constructor: autonomous custom elements must extend HTMLElement
```

Here `HTMLElement` is what all elements (eg: `HTMLDivElement`) inherit from.


**Autonomous custom element** can be defined and used in the following way:


```html
<script>
  class CustomElement extends HTMLElement {
    constructor() {
      super();
      // DOM is attached to the shadow root
      this.attachShadowRoot();

      // Additional code to define markup and functionality
    }
  }

  customElements.define('custom-element', CustomElement)
</script>


<!-- Can be used by defined name -->
<custom-element></custom-element>
```


**Customized built-in element** which extends a pre-existing HTML element is defined and used like so:


```html
<script>
  // Does not extend HTMLElement
  class CustomElement extends HTMLDivElement {
    constructor() {
      super();
      // Additional code to define markup and functionality
    }
  }

  // Need to mention extended element's tag name
  customElements.define('custom-element', CustomElement, { extends: 'div' })
</script>

<!-- Cannot be used by the defined name, requires `is` -->
<div is="custom-element"></div>
```

**Customized built-in element** is what is needed but the way it is used by having to resort to the `is` attribute makes it an unappealing choice.


**Autonomous custom elements** are unappealing cause of the use of Shadow DOM. Although it has a couple of advantages, multiple root elements, style encapsulation. 

Unfortunately style encapsulation also means that global styles are isolated from the Shadow DOM's scope. This can be circumvented by [linking the styles inside the Shadow DOM](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements#autonomous_custom_elements), perhaps I can add this in.

**Comment by 18alantom** [comment]
@nateabele closing this cause the style inheritance issue has been fixed. I suppose the Shadow DOM point can be a separate issue, although I'm unsure about how to fix it.
